PRAGMA foreign_keys = ON;
DROP TABLE IF EXISTS meterings;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS device_types;
DROP TABLE IF EXISTS units;
CREATE TABLE units (_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL);
CREATE TABLE device_types (_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, unit_id INTEGER, FOREIGN KEY(unit_id) REFERENCES units(_id));
CREATE TABLE devices (_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, device_type_id INTEGER, FOREIGN KEY(device_type_id) REFERENCES device_types(_id));
CREATE TABLE meterings (_id INTEGER PRIMARY KEY AUTOINCREMENT, created TEXT NOT NULL, measure REAL NOT NULL, device_id INTEGER, FOREIGN KEY(device_id) REFERENCES devices(_id));
DROP VIEW IF EXISTS summary;
CREATE VIEW summary AS SELECT devices._id AS device_id, devices.name AS device_name, meterings.measure AS last_measure, MAX(meterings.created) AS last_created FROM meterings LEFT JOIN devices ON meterings.device_id = devices._id GROUP BY meterings.device_id;